version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: postgres_database
    ports:
      - "6000:${DATABASE_PORT}"

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app_2
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
